### ISSUE TITLE
Not able to change layout to be Landscape

### ISSUE THREAD

**Issue by NehaGupta1992** [BALKANGraph/export-service#10]
I have used below code:

exportPDF({
        format: "A4",
        layout: "Landscape",
        scale: '40',
        header: "My chart",
        footer: 'Page {current-page} of {total-pages}'
      });

But, not able change the layout, rest all Ia m bale to change, but this orientation is not changing.

**Comment by ZornitsaSerbezova** [comment]
Hi NehaGupta1992,

This is the right way you should do it:

```
        chart.exportPDF({
            landscape: true, 
            layout: "Landscape",
            format: "A4",
            scale: '40',
            header: "My chart",
            footer: 'Page {current-page} of {total-pages}'
        });
```

**Comment by ZornitsaSerbezova** [comment]
Hi NehaGupta1992,

This is the right way you should do it:

```
        chart.exportPDF({
            landscape: true, 
            format: "A4",
            scale: '40',
            header: "My chart",
            footer: 'Page {current-page} of {total-pages}'
        });
```

**Comment by NehaGupta1992** [comment]
Hi,

Thanks, it is working now.

Best Regards,

*Neha Gupta*
Senior Software Engineer
w: KritiKalVision.ai <http://kritikalvision.ai/>
*e: *neha.gupta@kritikalvision.ai <shweta.srivastava@kritikalvision.ai>
