### ISSUE TITLE
Problem with the licensed edition. More than 200 unsupported nodes

### ISSUE THREAD

**Issue by M4R13L4** [BALKANGraph/export-service#21]
I downloaded the most updated version and followed the steps to replace them in the node_modules folder, in my local application it works perfectly but in production I get the error as if it was the free version. I tried to use the previous version together with the files that work fine and it still doesn't work.

**Comment by ZornitsaPesheva** [comment]
Please try to clean the browser cache / Ctrl+F5

**Comment by M4R13L4** [comment]
I did that before, but doesn't function

**Comment by ZornitsaPesheva** [comment]
Please write us on email about the issue from your registration email and we can have a meeting to check what is the issue.
