### ISSUE TITLE
OrgChart.pdfPrevUI.show not working in IE11

### ISSUE THREAD

**Issue by NehaGupta1992** [BALKANGraph/export-service#9]
The preview is not opening in IE11 browser.

**Comment by ZornitsaSerbezova** [comment]
Hi Neha,

Thank you for reporting the issue. We will take a look at it.

**Comment by ZornitsaSerbezova** [comment]
Fixed in version 7.1.5

**Comment by NehaGupta1992** [comment]
Yes it is fixed now.
